import React from 'react'
import Head from 'next/head'


function About() {
  setTimeout(function(){globalThis.location = '/progress'}, 2000);
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className='flex flex-col flex-auto justify-center items-center my-20'>
        <button className = "font-extrabold w-50 text-transparent text-8xl bg-clip-text bg-gradient-to-r from-indigo-400 via-cyan-400 to-white my-5 ">
            Who we are?</button>
        </div>    
        </div>
  )
   
}

export default About