import React from 'react'
import Head from 'next/head'
import Image from 'next/image'


function Contact() {
  return (
      <div className='flex flex-auto my-40'>
        <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-gradient-to-r from-cyan-500 via-green-600 to-indigo-500 w-[805px] mx-auto h-[805px]'>
        <div className='p-4 bg-black mx-1 my-2'>
        <div className='flex flex-col justify-center items-center relative top-2'>
        <button className = "font-extrabold w-50 text-transparent text-8xl bg-clip-text bg-gradient-to-r from-indigo-400 via-cyan-400 to-white my-5">
            Contact Us</button>
        </div>
          <div>
            <p className='text-center text-white text-2xl relative top-3'>Are you interested to know about our VR technology? <br/>
            Please fill out this form and we will contact you as soon as possible </p>
          </div>
          <div className='px-10 my-7 relative top-3'>
            <label className='text-white'>Your email</label>
            <input type="email" id="email" placeholder='your@email' className='w-full px-2 my-1' />
          </div>
          <div className='px-10'>
            <label className='text-white'>Subject</label>
            <input type="text" id="subject" placeholder='your subject' className='w-full px-2 my-1' />
          </div>
          <div className='px-10 my-5'>
            <label className='text-white'>Your message</label>
            <textarea type="textarea" id="message" placeholder='your message' className='block w-full px-2 my-1 h-60' />
          </div>
          <div className="my-8 relative top-1 left-9">
          <button className='bg-green-500 px-4 py-1.5 rounded-lg text-white hover:shadow-lg hover:bg-green-600'>Send message</button>
          </div>
      </div>
      </div>
      </div>
      )
}

export default Contact