import Head from 'next/head'
import Main from './main'

export default function Home() {
  return (
    <div>
    <div>
      <Head>
        <title>Virtual Hut</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
    <Main/>
    </div>
    

  )
}
