import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LandingHero from './components/Hero/LandingHero'
import LandingTeam from './components/Team/LandingTeam'
import DefaultLayout, { defaultLayout } from './layout/default'
import 'antd/dist/antd.css';

export default function Home() {
  return (
    <DefaultLayout>
      <div className={styles.container}>
        <Head>
          <title>Virtual Hut</title>

          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />

        </Head>
        <LandingHero />
        <LandingTeam />
      </div>
    </DefaultLayout>
  )
}

